version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose port 8000 inside the container to port 8000 on your machine
    env_file:
      - .env  # Load environment variables from the .env file
    volumes:
      - .:/app  # Mount the local directory to /app in the container
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "main:app"]  # Run with Gunicorn

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Copy your Nginx config
    ports:
      - "80:80"  # Expose port 80 for HTTP
    depends_on:
      - web  # Ensure the web service is up before Nginx starts